version: '3.8'
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network
    environment:
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_USER=guest

  eurekaserver:
    build: ./eurekaserver
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - network

  personnel-backend:
    build: ./personnelbackend
    container_name: personnel
    ports:
      - "8082:8082"
    depends_on:
      - eurekaserver
      - rabbitmq
    networks:
      - network
    environment:
      - EUREKA_HOST=eurekaserver
      - EUREKA_PORT=8761
      - RABBITMQ_HOST=rabbitmq

  notification-backend:
    build: ./notificationbackend
    container_name: notification
    ports:
      - "8080:8080"
    depends_on:
      - eurekaserver
      - rabbitmq
    networks:
      - network
    environment:
      - EUREKA_HOST=eurekaserver
      - EUREKA_PORT=8761
      - RABBITMQ_HOST=rabbitmq


  personnel-frontend:
    build: ./personnel-frontend
    container_name: personnel-frontend
    ports:
      - "3000:3000"
    depends_on:
      - personnel-backend
      - eurekaserver
    networks:
      - network

networks:
  network:
    driver: bridge
    name: network-test